<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="DiscordRichPresence" />
        <PackageReference Include="LibVLCSharp" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="TagLibSharp" />
        <PackageReference Include="ZLogger" />
    </ItemGroup>

</Project>
