# macOS (osx-x64 / osx-arm64) publish whitelist

[DeleteFolders]
video_chroma
video_filter
video_output
video_splitter
spu
text_renderer
visualization
mux
stream_out
access_output
keystore
services_discovery
stream_extractor
lua
misc
logger
meta_engine

[KeepInFolder:codec]
libmpg123_plugin
libflac_plugin
libopus_plugin
libvorbis_plugin
libddummy_plugin
libedummy_plugin

[KeepInFolder:access]
libfilesystem_plugin
