<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <PublishAot>true</PublishAot>
        <ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
        <IlcTreatWarningsAsErrors>false</IlcTreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Desktop" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <PackageReference Include="Avalonia.Wayland" />
        <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="LibVLCSharp" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
        <PackageReference Include="Svg.Controls.Skia.Avalonia" />
        <PackageReference Include="VideoLAN.LibVLC.Windows" />
        <PackageReference Include="ZLogger" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Core\Core.csproj" />
        <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
        <ProjectReference Include="..\Nexora.Theme\Nexora.Theme.csproj" />
    </ItemGroup>

    <ItemGroup>
        <TrimmerRootAssembly Include="DiscordRPC" />
    </ItemGroup>
</Project>
